//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KelioExporter.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://georges-helfer-sa.kelio.io/open/services/ClockingService")]
        public string KelioDataEx_ClockingServiceClient_ClockingService {
            get {
                return ((string)(this["KelioDataEx_ClockingServiceClient_ClockingService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://georges-helfer-sa.kelio.io/open/services/EmployeeProfessionalDataService")]
        public string KelioDataEx_EmployeeProfessionalDataServiceClient_EmployeeProfessionalDataService {
            get {
                return ((string)(this["KelioDataEx_EmployeeProfessionalDataServiceClient_EmployeeProfessionalDataService" +
                    ""]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://georges-helfer-sa.kelio.io/open/services/DailyScheduleAssignmentService")]
        public string KelioDataEx_DailyScheduleAssignmentServiceClient_DailyScheduleAssignmentService {
            get {
                return ((string)(this["KelioDataEx_DailyScheduleAssignmentServiceClient_DailyScheduleAssignmentService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://georges-helfer-sa.kelio.io/open/services/ClockingService")]
        public string KelioExporter_ClockingServiceClient1_ClockingService {
            get {
                return ((string)(this["KelioExporter_ClockingServiceClient1_ClockingService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://georges-helfer-sa.kelio.io/open/services/EmployeeProfessionalDataService")]
        public string KelioExporter_mployeeProfessionalDataServiceClient_EmployeeProfessionalDataService {
            get {
                return ((string)(this["KelioExporter_mployeeProfessionalDataServiceClient_EmployeeProfessionalDataServic" +
                    "e"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://georges-helfer-sa.kelio.io/open/services/DailyScheduleAssignmentService")]
        public string KelioExporter_DailyScheduleAssignmentServiceClient1_DailyScheduleAssignmentService {
            get {
                return ((string)(this["KelioExporter_DailyScheduleAssignmentServiceClient1_DailyScheduleAssignmentServic" +
                    "e"]));
            }
        }
    }
}
