//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Ce code source a été automatiquement généré par Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace KelioExporter.DailyScheduleAssignmentServiceClient1 {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DailyScheduleAssignmentServiceSoapBinding", Namespace="http://echange.service.open.bodet.com")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Object))]
    public partial class DailyScheduleAssignmentService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback exportDailyScheduleAssignmentsOperationCompleted;
        
        private System.Threading.SendOrPostCallback exportDailyScheduleAssignmentsFromEmployeeListOperationCompleted;
        
        private System.Threading.SendOrPostCallback importDailyScheduleAssignmentsOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteDailyScheduleAssignmentsOperationCompleted;
        
        private System.Threading.SendOrPostCallback exportDailyScheduleAssignmentsListOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DailyScheduleAssignmentService() {
            this.Url = global::KelioExporter.Properties.Settings.Default.KelioExporter_DailyScheduleAssignmentServiceClient1_DailyScheduleAssignmentService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event exportDailyScheduleAssignmentsCompletedEventHandler exportDailyScheduleAssignmentsCompleted;
        
        /// <remarks/>
        public event exportDailyScheduleAssignmentsFromEmployeeListCompletedEventHandler exportDailyScheduleAssignmentsFromEmployeeListCompleted;
        
        /// <remarks/>
        public event importDailyScheduleAssignmentsCompletedEventHandler importDailyScheduleAssignmentsCompleted;
        
        /// <remarks/>
        public event deleteDailyScheduleAssignmentsCompletedEventHandler deleteDailyScheduleAssignmentsCompleted;
        
        /// <remarks/>
        public event exportDailyScheduleAssignmentsListCompletedEventHandler exportDailyScheduleAssignmentsListCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:exportDailyScheduleAssignments", RequestNamespace="http://echange.service.open.bodet.com", ResponseNamespace="http://echange.service.open.bodet.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("exportedDailyScheduleAssignments")]
        public DailyScheduleAssignment[] exportDailyScheduleAssignments([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string populationFilter, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string groupFilter, [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)] System.Nullable<System.DateTime> startDate, [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool startDateSpecified, [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)] System.Nullable<System.DateTime> endDate, [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool endDateSpecified) {
            object[] results = this.Invoke("exportDailyScheduleAssignments", new object[] {
                        populationFilter,
                        groupFilter,
                        startDate,
                        startDateSpecified,
                        endDate,
                        endDateSpecified});
            return ((DailyScheduleAssignment[])(results[0]));
        }
        
        /// <remarks/>
        public void exportDailyScheduleAssignmentsAsync(string populationFilter, string groupFilter, System.Nullable<System.DateTime> startDate, bool startDateSpecified, System.Nullable<System.DateTime> endDate, bool endDateSpecified) {
            this.exportDailyScheduleAssignmentsAsync(populationFilter, groupFilter, startDate, startDateSpecified, endDate, endDateSpecified, null);
        }
        
        /// <remarks/>
        public void exportDailyScheduleAssignmentsAsync(string populationFilter, string groupFilter, System.Nullable<System.DateTime> startDate, bool startDateSpecified, System.Nullable<System.DateTime> endDate, bool endDateSpecified, object userState) {
            if ((this.exportDailyScheduleAssignmentsOperationCompleted == null)) {
                this.exportDailyScheduleAssignmentsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnexportDailyScheduleAssignmentsOperationCompleted);
            }
            this.InvokeAsync("exportDailyScheduleAssignments", new object[] {
                        populationFilter,
                        groupFilter,
                        startDate,
                        startDateSpecified,
                        endDate,
                        endDateSpecified}, this.exportDailyScheduleAssignmentsOperationCompleted, userState);
        }
        
        private void OnexportDailyScheduleAssignmentsOperationCompleted(object arg) {
            if ((this.exportDailyScheduleAssignmentsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.exportDailyScheduleAssignmentsCompleted(this, new exportDailyScheduleAssignmentsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:exportDailyScheduleAssignmentsFromEmployeeList", RequestNamespace="http://echange.service.open.bodet.com", ResponseNamespace="http://echange.service.open.bodet.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("exportedDailyScheduleAssignments")]
        public DailyScheduleAssignment[] exportDailyScheduleAssignmentsFromEmployeeList(askedEmployee[] employeeList) {
            object[] results = this.Invoke("exportDailyScheduleAssignmentsFromEmployeeList", new object[] {
                        employeeList});
            return ((DailyScheduleAssignment[])(results[0]));
        }
        
        /// <remarks/>
        public void exportDailyScheduleAssignmentsFromEmployeeListAsync(askedEmployee[] employeeList) {
            this.exportDailyScheduleAssignmentsFromEmployeeListAsync(employeeList, null);
        }
        
        /// <remarks/>
        public void exportDailyScheduleAssignmentsFromEmployeeListAsync(askedEmployee[] employeeList, object userState) {
            if ((this.exportDailyScheduleAssignmentsFromEmployeeListOperationCompleted == null)) {
                this.exportDailyScheduleAssignmentsFromEmployeeListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnexportDailyScheduleAssignmentsFromEmployeeListOperationCompleted);
            }
            this.InvokeAsync("exportDailyScheduleAssignmentsFromEmployeeList", new object[] {
                        employeeList}, this.exportDailyScheduleAssignmentsFromEmployeeListOperationCompleted, userState);
        }
        
        private void OnexportDailyScheduleAssignmentsFromEmployeeListOperationCompleted(object arg) {
            if ((this.exportDailyScheduleAssignmentsFromEmployeeListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.exportDailyScheduleAssignmentsFromEmployeeListCompleted(this, new exportDailyScheduleAssignmentsFromEmployeeListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:importDailyScheduleAssignments", RequestNamespace="http://echange.service.open.bodet.com", ResponseNamespace="http://echange.service.open.bodet.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("dailyScheduleAssignmentsInError")]
        public DailyScheduleAssignment[] importDailyScheduleAssignments(DailyScheduleAssignment[] dailyScheduleAssignmentsToImport) {
            object[] results = this.Invoke("importDailyScheduleAssignments", new object[] {
                        dailyScheduleAssignmentsToImport});
            return ((DailyScheduleAssignment[])(results[0]));
        }
        
        /// <remarks/>
        public void importDailyScheduleAssignmentsAsync(DailyScheduleAssignment[] dailyScheduleAssignmentsToImport) {
            this.importDailyScheduleAssignmentsAsync(dailyScheduleAssignmentsToImport, null);
        }
        
        /// <remarks/>
        public void importDailyScheduleAssignmentsAsync(DailyScheduleAssignment[] dailyScheduleAssignmentsToImport, object userState) {
            if ((this.importDailyScheduleAssignmentsOperationCompleted == null)) {
                this.importDailyScheduleAssignmentsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnimportDailyScheduleAssignmentsOperationCompleted);
            }
            this.InvokeAsync("importDailyScheduleAssignments", new object[] {
                        dailyScheduleAssignmentsToImport}, this.importDailyScheduleAssignmentsOperationCompleted, userState);
        }
        
        private void OnimportDailyScheduleAssignmentsOperationCompleted(object arg) {
            if ((this.importDailyScheduleAssignmentsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.importDailyScheduleAssignmentsCompleted(this, new importDailyScheduleAssignmentsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:deleteDailyScheduleAssignments", RequestNamespace="http://echange.service.open.bodet.com", ResponseNamespace="http://echange.service.open.bodet.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("dailyScheduleAssignmentsInError")]
        public DailyScheduleAssignment[] deleteDailyScheduleAssignments(DailyScheduleAssignment[] dailyScheduleAssignmentsToDelete) {
            object[] results = this.Invoke("deleteDailyScheduleAssignments", new object[] {
                        dailyScheduleAssignmentsToDelete});
            return ((DailyScheduleAssignment[])(results[0]));
        }
        
        /// <remarks/>
        public void deleteDailyScheduleAssignmentsAsync(DailyScheduleAssignment[] dailyScheduleAssignmentsToDelete) {
            this.deleteDailyScheduleAssignmentsAsync(dailyScheduleAssignmentsToDelete, null);
        }
        
        /// <remarks/>
        public void deleteDailyScheduleAssignmentsAsync(DailyScheduleAssignment[] dailyScheduleAssignmentsToDelete, object userState) {
            if ((this.deleteDailyScheduleAssignmentsOperationCompleted == null)) {
                this.deleteDailyScheduleAssignmentsOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteDailyScheduleAssignmentsOperationCompleted);
            }
            this.InvokeAsync("deleteDailyScheduleAssignments", new object[] {
                        dailyScheduleAssignmentsToDelete}, this.deleteDailyScheduleAssignmentsOperationCompleted, userState);
        }
        
        private void OndeleteDailyScheduleAssignmentsOperationCompleted(object arg) {
            if ((this.deleteDailyScheduleAssignmentsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteDailyScheduleAssignmentsCompleted(this, new deleteDailyScheduleAssignmentsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:exportDailyScheduleAssignmentsList", RequestNamespace="http://echange.service.open.bodet.com", ResponseNamespace="http://echange.service.open.bodet.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("exportedDailyScheduleAssignments")]
        public DailyScheduleAssignment[] exportDailyScheduleAssignmentsList(AskedPopulationWithPeriod[] populationFilter) {
            object[] results = this.Invoke("exportDailyScheduleAssignmentsList", new object[] {
                        populationFilter});
            return ((DailyScheduleAssignment[])(results[0]));
        }
        
        /// <remarks/>
        public void exportDailyScheduleAssignmentsListAsync(AskedPopulationWithPeriod[] populationFilter) {
            this.exportDailyScheduleAssignmentsListAsync(populationFilter, null);
        }
        
        /// <remarks/>
        public void exportDailyScheduleAssignmentsListAsync(AskedPopulationWithPeriod[] populationFilter, object userState) {
            if ((this.exportDailyScheduleAssignmentsListOperationCompleted == null)) {
                this.exportDailyScheduleAssignmentsListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnexportDailyScheduleAssignmentsListOperationCompleted);
            }
            this.InvokeAsync("exportDailyScheduleAssignmentsList", new object[] {
                        populationFilter}, this.exportDailyScheduleAssignmentsListOperationCompleted, userState);
        }
        
        private void OnexportDailyScheduleAssignmentsListOperationCompleted(object arg) {
            if ((this.exportDailyScheduleAssignmentsListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.exportDailyScheduleAssignmentsListCompleted(this, new exportDailyScheduleAssignmentsListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://echange.service.open.bodet.com")]
    public partial class DailyScheduleAssignment : EmployeeInformation {
        
        private System.Nullable<int> calculationModeContractedScheduleField;
        
        private bool calculationModeContractedScheduleFieldSpecified;
        
        private string scheduleAbbreviationField;
        
        private System.Nullable<int> fourthWorkingPeriodEndTimePositionField;
        
        private bool fourthWorkingPeriodEndTimePositionFieldSpecified;
        
        private System.Nullable<int> fifthWorkingPeriodEndTimePositionField;
        
        private bool fifthWorkingPeriodEndTimePositionFieldSpecified;
        
        private System.Nullable<int> fifthWorkingPeriodStartTimePositionField;
        
        private bool fifthWorkingPeriodStartTimePositionFieldSpecified;
        
        private System.Nullable<int> firstWorkingPeriodEndTimePositionField;
        
        private bool firstWorkingPeriodEndTimePositionFieldSpecified;
        
        private System.Nullable<int> firstWorkingPeriodStartTimePositionField;
        
        private bool firstWorkingPeriodStartTimePositionFieldSpecified;
        
        private System.Nullable<System.DateTime> nightStartTimeField;
        
        private bool nightStartTimeFieldSpecified;
        
        private System.Nullable<int> secondWorkingPeriodStartTimePositionField;
        
        private bool secondWorkingPeriodStartTimePositionFieldSpecified;
        
        private System.Nullable<int> fourthWorkingPeriodStartTimePositionField;
        
        private bool fourthWorkingPeriodStartTimePositionFieldSpecified;
        
        private System.Nullable<int> thirdWorkingPeriodStartTimePositionField;
        
        private bool thirdWorkingPeriodStartTimePositionFieldSpecified;
        
        private System.Nullable<int> thirdWorkingPeriodEndTimePositionField;
        
        private bool thirdWorkingPeriodEndTimePositionFieldSpecified;
        
        private System.Nullable<int> secondWorkingPeriodEndTimePositionField;
        
        private bool secondWorkingPeriodEndTimePositionFieldSpecified;
        
        private System.Nullable<System.DateTime> halfDayTimeField;
        
        private bool halfDayTimeFieldSpecified;
        
        private System.Nullable<System.DateTime> secondWorkingPeriodEndTimeField;
        
        private bool secondWorkingPeriodEndTimeFieldSpecified;
        
        private System.Nullable<System.DateTime> thirdWorkingPeriodEndTimeField;
        
        private bool thirdWorkingPeriodEndTimeFieldSpecified;
        
        private System.Nullable<System.DateTime> fifthWorkingPeriodEndTimeField;
        
        private bool fifthWorkingPeriodEndTimeFieldSpecified;
        
        private System.Nullable<System.DateTime> thirdWorkingPeriodStartTimeField;
        
        private bool thirdWorkingPeriodStartTimeFieldSpecified;
        
        private System.Nullable<System.DateTime> firstWorkingPeriodStartTimeField;
        
        private bool firstWorkingPeriodStartTimeFieldSpecified;
        
        private System.Nullable<System.DateTime> secondWorkingPeriodStartTimeField;
        
        private bool secondWorkingPeriodStartTimeFieldSpecified;
        
        private System.Nullable<System.DateTime> fifthWorkingPeriodStartTimeField;
        
        private bool fifthWorkingPeriodStartTimeFieldSpecified;
        
        private System.Nullable<System.DateTime> firstWorkingPeriodEndTimeField;
        
        private bool firstWorkingPeriodEndTimeFieldSpecified;
        
        private System.Nullable<System.DateTime> fourthWorkingPeriodEndTimeField;
        
        private bool fourthWorkingPeriodEndTimeFieldSpecified;
        
        private System.Nullable<System.DateTime> fourthWorkingPeriodStartTimeField;
        
        private bool fourthWorkingPeriodStartTimeFieldSpecified;
        
        private System.Nullable<short> nightStartTimePositionField;
        
        private bool nightStartTimePositionFieldSpecified;
        
        private string commentField;
        
        private System.Nullable<double> afternoonContractedTimeField;
        
        private bool afternoonContractedTimeFieldSpecified;
        
        private System.Nullable<double> morningContractedTimeField;
        
        private bool morningContractedTimeFieldSpecified;
        
        private System.Nullable<System.DateTime> assignmentDateField;
        
        private bool assignmentDateFieldSpecified;
        
        private System.Nullable<double> contractedTimeField;
        
        private bool contractedTimeFieldSpecified;
        
        private System.Nullable<bool> assignementByExceptionField;
        
        private bool assignementByExceptionFieldSpecified;
        
        private System.Nullable<bool> contractedFromWorkingPeriodsField;
        
        private bool contractedFromWorkingPeriodsFieldSpecified;
        
        private string scheduleDescriptionField;
        
        private string dailyScheduleAbbreviationField;
        
        private System.Nullable<int> dailyScheduleKeyField;
        
        private bool dailyScheduleKeyFieldSpecified;
        
        private string dailyScheduleDescriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> calculationModeContractedSchedule {
            get {
                return this.calculationModeContractedScheduleField;
            }
            set {
                this.calculationModeContractedScheduleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool calculationModeContractedScheduleSpecified {
            get {
                return this.calculationModeContractedScheduleFieldSpecified;
            }
            set {
                this.calculationModeContractedScheduleFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string scheduleAbbreviation {
            get {
                return this.scheduleAbbreviationField;
            }
            set {
                this.scheduleAbbreviationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> fourthWorkingPeriodEndTimePosition {
            get {
                return this.fourthWorkingPeriodEndTimePositionField;
            }
            set {
                this.fourthWorkingPeriodEndTimePositionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fourthWorkingPeriodEndTimePositionSpecified {
            get {
                return this.fourthWorkingPeriodEndTimePositionFieldSpecified;
            }
            set {
                this.fourthWorkingPeriodEndTimePositionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> fifthWorkingPeriodEndTimePosition {
            get {
                return this.fifthWorkingPeriodEndTimePositionField;
            }
            set {
                this.fifthWorkingPeriodEndTimePositionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fifthWorkingPeriodEndTimePositionSpecified {
            get {
                return this.fifthWorkingPeriodEndTimePositionFieldSpecified;
            }
            set {
                this.fifthWorkingPeriodEndTimePositionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> fifthWorkingPeriodStartTimePosition {
            get {
                return this.fifthWorkingPeriodStartTimePositionField;
            }
            set {
                this.fifthWorkingPeriodStartTimePositionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fifthWorkingPeriodStartTimePositionSpecified {
            get {
                return this.fifthWorkingPeriodStartTimePositionFieldSpecified;
            }
            set {
                this.fifthWorkingPeriodStartTimePositionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> firstWorkingPeriodEndTimePosition {
            get {
                return this.firstWorkingPeriodEndTimePositionField;
            }
            set {
                this.firstWorkingPeriodEndTimePositionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool firstWorkingPeriodEndTimePositionSpecified {
            get {
                return this.firstWorkingPeriodEndTimePositionFieldSpecified;
            }
            set {
                this.firstWorkingPeriodEndTimePositionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> firstWorkingPeriodStartTimePosition {
            get {
                return this.firstWorkingPeriodStartTimePositionField;
            }
            set {
                this.firstWorkingPeriodStartTimePositionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool firstWorkingPeriodStartTimePositionSpecified {
            get {
                return this.firstWorkingPeriodStartTimePositionFieldSpecified;
            }
            set {
                this.firstWorkingPeriodStartTimePositionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="time", IsNullable=true)]
        public System.Nullable<System.DateTime> nightStartTime {
            get {
                return this.nightStartTimeField;
            }
            set {
                this.nightStartTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nightStartTimeSpecified {
            get {
                return this.nightStartTimeFieldSpecified;
            }
            set {
                this.nightStartTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> secondWorkingPeriodStartTimePosition {
            get {
                return this.secondWorkingPeriodStartTimePositionField;
            }
            set {
                this.secondWorkingPeriodStartTimePositionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool secondWorkingPeriodStartTimePositionSpecified {
            get {
                return this.secondWorkingPeriodStartTimePositionFieldSpecified;
            }
            set {
                this.secondWorkingPeriodStartTimePositionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> fourthWorkingPeriodStartTimePosition {
            get {
                return this.fourthWorkingPeriodStartTimePositionField;
            }
            set {
                this.fourthWorkingPeriodStartTimePositionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fourthWorkingPeriodStartTimePositionSpecified {
            get {
                return this.fourthWorkingPeriodStartTimePositionFieldSpecified;
            }
            set {
                this.fourthWorkingPeriodStartTimePositionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> thirdWorkingPeriodStartTimePosition {
            get {
                return this.thirdWorkingPeriodStartTimePositionField;
            }
            set {
                this.thirdWorkingPeriodStartTimePositionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool thirdWorkingPeriodStartTimePositionSpecified {
            get {
                return this.thirdWorkingPeriodStartTimePositionFieldSpecified;
            }
            set {
                this.thirdWorkingPeriodStartTimePositionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> thirdWorkingPeriodEndTimePosition {
            get {
                return this.thirdWorkingPeriodEndTimePositionField;
            }
            set {
                this.thirdWorkingPeriodEndTimePositionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool thirdWorkingPeriodEndTimePositionSpecified {
            get {
                return this.thirdWorkingPeriodEndTimePositionFieldSpecified;
            }
            set {
                this.thirdWorkingPeriodEndTimePositionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> secondWorkingPeriodEndTimePosition {
            get {
                return this.secondWorkingPeriodEndTimePositionField;
            }
            set {
                this.secondWorkingPeriodEndTimePositionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool secondWorkingPeriodEndTimePositionSpecified {
            get {
                return this.secondWorkingPeriodEndTimePositionFieldSpecified;
            }
            set {
                this.secondWorkingPeriodEndTimePositionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="time", IsNullable=true)]
        public System.Nullable<System.DateTime> halfDayTime {
            get {
                return this.halfDayTimeField;
            }
            set {
                this.halfDayTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool halfDayTimeSpecified {
            get {
                return this.halfDayTimeFieldSpecified;
            }
            set {
                this.halfDayTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="time", IsNullable=true)]
        public System.Nullable<System.DateTime> secondWorkingPeriodEndTime {
            get {
                return this.secondWorkingPeriodEndTimeField;
            }
            set {
                this.secondWorkingPeriodEndTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool secondWorkingPeriodEndTimeSpecified {
            get {
                return this.secondWorkingPeriodEndTimeFieldSpecified;
            }
            set {
                this.secondWorkingPeriodEndTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="time", IsNullable=true)]
        public System.Nullable<System.DateTime> thirdWorkingPeriodEndTime {
            get {
                return this.thirdWorkingPeriodEndTimeField;
            }
            set {
                this.thirdWorkingPeriodEndTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool thirdWorkingPeriodEndTimeSpecified {
            get {
                return this.thirdWorkingPeriodEndTimeFieldSpecified;
            }
            set {
                this.thirdWorkingPeriodEndTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="time", IsNullable=true)]
        public System.Nullable<System.DateTime> fifthWorkingPeriodEndTime {
            get {
                return this.fifthWorkingPeriodEndTimeField;
            }
            set {
                this.fifthWorkingPeriodEndTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fifthWorkingPeriodEndTimeSpecified {
            get {
                return this.fifthWorkingPeriodEndTimeFieldSpecified;
            }
            set {
                this.fifthWorkingPeriodEndTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="time", IsNullable=true)]
        public System.Nullable<System.DateTime> thirdWorkingPeriodStartTime {
            get {
                return this.thirdWorkingPeriodStartTimeField;
            }
            set {
                this.thirdWorkingPeriodStartTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool thirdWorkingPeriodStartTimeSpecified {
            get {
                return this.thirdWorkingPeriodStartTimeFieldSpecified;
            }
            set {
                this.thirdWorkingPeriodStartTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="time", IsNullable=true)]
        public System.Nullable<System.DateTime> firstWorkingPeriodStartTime {
            get {
                return this.firstWorkingPeriodStartTimeField;
            }
            set {
                this.firstWorkingPeriodStartTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool firstWorkingPeriodStartTimeSpecified {
            get {
                return this.firstWorkingPeriodStartTimeFieldSpecified;
            }
            set {
                this.firstWorkingPeriodStartTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="time", IsNullable=true)]
        public System.Nullable<System.DateTime> secondWorkingPeriodStartTime {
            get {
                return this.secondWorkingPeriodStartTimeField;
            }
            set {
                this.secondWorkingPeriodStartTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool secondWorkingPeriodStartTimeSpecified {
            get {
                return this.secondWorkingPeriodStartTimeFieldSpecified;
            }
            set {
                this.secondWorkingPeriodStartTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="time", IsNullable=true)]
        public System.Nullable<System.DateTime> fifthWorkingPeriodStartTime {
            get {
                return this.fifthWorkingPeriodStartTimeField;
            }
            set {
                this.fifthWorkingPeriodStartTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fifthWorkingPeriodStartTimeSpecified {
            get {
                return this.fifthWorkingPeriodStartTimeFieldSpecified;
            }
            set {
                this.fifthWorkingPeriodStartTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="time", IsNullable=true)]
        public System.Nullable<System.DateTime> firstWorkingPeriodEndTime {
            get {
                return this.firstWorkingPeriodEndTimeField;
            }
            set {
                this.firstWorkingPeriodEndTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool firstWorkingPeriodEndTimeSpecified {
            get {
                return this.firstWorkingPeriodEndTimeFieldSpecified;
            }
            set {
                this.firstWorkingPeriodEndTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="time", IsNullable=true)]
        public System.Nullable<System.DateTime> fourthWorkingPeriodEndTime {
            get {
                return this.fourthWorkingPeriodEndTimeField;
            }
            set {
                this.fourthWorkingPeriodEndTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fourthWorkingPeriodEndTimeSpecified {
            get {
                return this.fourthWorkingPeriodEndTimeFieldSpecified;
            }
            set {
                this.fourthWorkingPeriodEndTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="time", IsNullable=true)]
        public System.Nullable<System.DateTime> fourthWorkingPeriodStartTime {
            get {
                return this.fourthWorkingPeriodStartTimeField;
            }
            set {
                this.fourthWorkingPeriodStartTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fourthWorkingPeriodStartTimeSpecified {
            get {
                return this.fourthWorkingPeriodStartTimeFieldSpecified;
            }
            set {
                this.fourthWorkingPeriodStartTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<short> nightStartTimePosition {
            get {
                return this.nightStartTimePositionField;
            }
            set {
                this.nightStartTimePositionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nightStartTimePositionSpecified {
            get {
                return this.nightStartTimePositionFieldSpecified;
            }
            set {
                this.nightStartTimePositionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> afternoonContractedTime {
            get {
                return this.afternoonContractedTimeField;
            }
            set {
                this.afternoonContractedTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool afternoonContractedTimeSpecified {
            get {
                return this.afternoonContractedTimeFieldSpecified;
            }
            set {
                this.afternoonContractedTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> morningContractedTime {
            get {
                return this.morningContractedTimeField;
            }
            set {
                this.morningContractedTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool morningContractedTimeSpecified {
            get {
                return this.morningContractedTimeFieldSpecified;
            }
            set {
                this.morningContractedTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
        public System.Nullable<System.DateTime> assignmentDate {
            get {
                return this.assignmentDateField;
            }
            set {
                this.assignmentDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool assignmentDateSpecified {
            get {
                return this.assignmentDateFieldSpecified;
            }
            set {
                this.assignmentDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> contractedTime {
            get {
                return this.contractedTimeField;
            }
            set {
                this.contractedTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool contractedTimeSpecified {
            get {
                return this.contractedTimeFieldSpecified;
            }
            set {
                this.contractedTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> assignementByException {
            get {
                return this.assignementByExceptionField;
            }
            set {
                this.assignementByExceptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool assignementByExceptionSpecified {
            get {
                return this.assignementByExceptionFieldSpecified;
            }
            set {
                this.assignementByExceptionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> contractedFromWorkingPeriods {
            get {
                return this.contractedFromWorkingPeriodsField;
            }
            set {
                this.contractedFromWorkingPeriodsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool contractedFromWorkingPeriodsSpecified {
            get {
                return this.contractedFromWorkingPeriodsFieldSpecified;
            }
            set {
                this.contractedFromWorkingPeriodsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string scheduleDescription {
            get {
                return this.scheduleDescriptionField;
            }
            set {
                this.scheduleDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string dailyScheduleAbbreviation {
            get {
                return this.dailyScheduleAbbreviationField;
            }
            set {
                this.dailyScheduleAbbreviationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> dailyScheduleKey {
            get {
                return this.dailyScheduleKeyField;
            }
            set {
                this.dailyScheduleKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dailyScheduleKeySpecified {
            get {
                return this.dailyScheduleKeyFieldSpecified;
            }
            set {
                this.dailyScheduleKeyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string dailyScheduleDescription {
            get {
                return this.dailyScheduleDescriptionField;
            }
            set {
                this.dailyScheduleDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AskedPopulation))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AskedPopulationWithPeriod))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(askedEmployee))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DailyScheduleAssignment))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://echange.service.open.bodet.com")]
    public partial class EmployeeInformation : Object {
        
        private string employeeIdentificationNumberField;
        
        private System.Nullable<bool> archivedEmployeeField;
        
        private bool archivedEmployeeFieldSpecified;
        
        private string employeeIdentificationCodeField;
        
        private string employeeBadgeCodeField;
        
        private System.Nullable<int> employeeKeyField;
        
        private bool employeeKeyFieldSpecified;
        
        private string employeeSurnameField;
        
        private string employeeFirstNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string employeeIdentificationNumber {
            get {
                return this.employeeIdentificationNumberField;
            }
            set {
                this.employeeIdentificationNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> archivedEmployee {
            get {
                return this.archivedEmployeeField;
            }
            set {
                this.archivedEmployeeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool archivedEmployeeSpecified {
            get {
                return this.archivedEmployeeFieldSpecified;
            }
            set {
                this.archivedEmployeeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string employeeIdentificationCode {
            get {
                return this.employeeIdentificationCodeField;
            }
            set {
                this.employeeIdentificationCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string employeeBadgeCode {
            get {
                return this.employeeBadgeCodeField;
            }
            set {
                this.employeeBadgeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> employeeKey {
            get {
                return this.employeeKeyField;
            }
            set {
                this.employeeKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool employeeKeySpecified {
            get {
                return this.employeeKeyFieldSpecified;
            }
            set {
                this.employeeKeyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string employeeSurname {
            get {
                return this.employeeSurnameField;
            }
            set {
                this.employeeSurnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string employeeFirstName {
            get {
                return this.employeeFirstNameField;
            }
            set {
                this.employeeFirstNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EmployeeInformation))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AskedPopulation))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AskedPopulationWithPeriod))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(askedEmployee))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DailyScheduleAssignment))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://echange.service.open.bodet.com")]
    public abstract partial class Object {
        
        private string errorMessageField;
        
        private string technicalStringField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string technicalString {
            get {
                return this.technicalStringField;
            }
            set {
                this.technicalStringField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AskedPopulationWithPeriod))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://echange.service.open.bodet.com")]
    public partial class AskedPopulation : EmployeeInformation {
        
        private System.Nullable<System.DateTime> populationStartDateField;
        
        private bool populationStartDateFieldSpecified;
        
        private System.Nullable<System.DateTime> populationEndDateField;
        
        private bool populationEndDateFieldSpecified;
        
        private string populationFilterField;
        
        private string groupFilterField;
        
        private System.Nullable<int> populationModeField;
        
        private bool populationModeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
        public System.Nullable<System.DateTime> populationStartDate {
            get {
                return this.populationStartDateField;
            }
            set {
                this.populationStartDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool populationStartDateSpecified {
            get {
                return this.populationStartDateFieldSpecified;
            }
            set {
                this.populationStartDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
        public System.Nullable<System.DateTime> populationEndDate {
            get {
                return this.populationEndDateField;
            }
            set {
                this.populationEndDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool populationEndDateSpecified {
            get {
                return this.populationEndDateFieldSpecified;
            }
            set {
                this.populationEndDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string populationFilter {
            get {
                return this.populationFilterField;
            }
            set {
                this.populationFilterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string groupFilter {
            get {
                return this.groupFilterField;
            }
            set {
                this.groupFilterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> populationMode {
            get {
                return this.populationModeField;
            }
            set {
                this.populationModeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool populationModeSpecified {
            get {
                return this.populationModeFieldSpecified;
            }
            set {
                this.populationModeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://echange.service.open.bodet.com")]
    public partial class AskedPopulationWithPeriod : AskedPopulation {
        
        private System.Nullable<System.DateTime> endDateField;
        
        private bool endDateFieldSpecified;
        
        private System.Nullable<System.DateTime> startDateField;
        
        private bool startDateFieldSpecified;
        
        private System.Nullable<int> startOffsetField;
        
        private bool startOffsetFieldSpecified;
        
        private System.Nullable<int> endOffsetField;
        
        private bool endOffsetFieldSpecified;
        
        private System.Nullable<int> dateModeField;
        
        private bool dateModeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
        public System.Nullable<System.DateTime> endDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool endDateSpecified {
            get {
                return this.endDateFieldSpecified;
            }
            set {
                this.endDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
        public System.Nullable<System.DateTime> startDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startDateSpecified {
            get {
                return this.startDateFieldSpecified;
            }
            set {
                this.startDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> startOffset {
            get {
                return this.startOffsetField;
            }
            set {
                this.startOffsetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startOffsetSpecified {
            get {
                return this.startOffsetFieldSpecified;
            }
            set {
                this.startOffsetFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> endOffset {
            get {
                return this.endOffsetField;
            }
            set {
                this.endOffsetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool endOffsetSpecified {
            get {
                return this.endOffsetFieldSpecified;
            }
            set {
                this.endOffsetFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> dateMode {
            get {
                return this.dateModeField;
            }
            set {
                this.dateModeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateModeSpecified {
            get {
                return this.dateModeFieldSpecified;
            }
            set {
                this.dateModeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://echange.service.open.bodet.com")]
    public partial class askedEmployee : EmployeeInformation {
        
        private System.Nullable<System.DateTime> endDateField;
        
        private bool endDateFieldSpecified;
        
        private System.Nullable<System.DateTime> startDateField;
        
        private bool startDateFieldSpecified;
        
        private System.Nullable<int> startOffsetField;
        
        private bool startOffsetFieldSpecified;
        
        private System.Nullable<int> endOffsetField;
        
        private bool endOffsetFieldSpecified;
        
        private System.Nullable<int> dateModeField;
        
        private bool dateModeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
        public System.Nullable<System.DateTime> endDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool endDateSpecified {
            get {
                return this.endDateFieldSpecified;
            }
            set {
                this.endDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
        public System.Nullable<System.DateTime> startDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startDateSpecified {
            get {
                return this.startDateFieldSpecified;
            }
            set {
                this.startDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> startOffset {
            get {
                return this.startOffsetField;
            }
            set {
                this.startOffsetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startOffsetSpecified {
            get {
                return this.startOffsetFieldSpecified;
            }
            set {
                this.startOffsetFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> endOffset {
            get {
                return this.endOffsetField;
            }
            set {
                this.endOffsetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool endOffsetSpecified {
            get {
                return this.endOffsetFieldSpecified;
            }
            set {
                this.endOffsetFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> dateMode {
            get {
                return this.dateModeField;
            }
            set {
                this.dateModeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateModeSpecified {
            get {
                return this.dateModeFieldSpecified;
            }
            set {
                this.dateModeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void exportDailyScheduleAssignmentsCompletedEventHandler(object sender, exportDailyScheduleAssignmentsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class exportDailyScheduleAssignmentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal exportDailyScheduleAssignmentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DailyScheduleAssignment[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DailyScheduleAssignment[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void exportDailyScheduleAssignmentsFromEmployeeListCompletedEventHandler(object sender, exportDailyScheduleAssignmentsFromEmployeeListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class exportDailyScheduleAssignmentsFromEmployeeListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal exportDailyScheduleAssignmentsFromEmployeeListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DailyScheduleAssignment[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DailyScheduleAssignment[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void importDailyScheduleAssignmentsCompletedEventHandler(object sender, importDailyScheduleAssignmentsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class importDailyScheduleAssignmentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal importDailyScheduleAssignmentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DailyScheduleAssignment[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DailyScheduleAssignment[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void deleteDailyScheduleAssignmentsCompletedEventHandler(object sender, deleteDailyScheduleAssignmentsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteDailyScheduleAssignmentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteDailyScheduleAssignmentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DailyScheduleAssignment[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DailyScheduleAssignment[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void exportDailyScheduleAssignmentsListCompletedEventHandler(object sender, exportDailyScheduleAssignmentsListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class exportDailyScheduleAssignmentsListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal exportDailyScheduleAssignmentsListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DailyScheduleAssignment[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DailyScheduleAssignment[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591